OpenGMS/urls.py
import notifications
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views import generic
import notifications.urls

from core import views as core_views
from autocompleteAPI import views as autocomplete_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', core_views.home, name='home'),
    # url(r'^login', generic.FormView.as_view(
    #     form_class=core_form.LogInForm, template_name="core/base_form.html",success_url='loginpost'), name="login"),
    url(r'^login', core_views.loginview, name='login'),
    url(r'^logout', core_views.logoutview, name='logout'),
    # url(r'^login', auth_views.login, {'template_name': 'core/login.html'},
    #     name='login'),
    url(r'^auth/', include('authentication.urls')),
    url(r'^officer/', include('officer.urls')),
    url(r'^client/', include('client.urls')),
    url(r'^production/', include('production.urls')),
    url(r'^service/', include('service.urls')),

    # notification
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # rest API for autocomplete
    url('^api/clients/', autocomplete_views.list, name='clientsAPI'),

]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

client/urls.py
from django.conf.urls import url
from django.views import generic
import client.views as client_views

app_name = 'client'

urlpatterns = [
    url(r'^$', client_views.personal_info, name='personal_info'),
    url(r'^profile', client_views.profile, name='profile'),
    url(r'^contact', client_views.contact, name='contact'),
    url(r'^picture', client_views.picture, name='picture'),
    url(r'^password', client_views.password, name='password'),

    # url(r'^create_account', client_views.create_account, name='create_account'),
    # url(r'^delete_account', client_views.delete_account, name='delete_account'),
    # url(r'^reset_account_pass', client_views.reset_account_pass, name='reset_account_pass'),

    url(r'^new_order', client_views.new_order, name='new_order'),
    url(r'^view_order/(?P<pk>[0-9]+)$', client_views.view_order, name='view_order'),
    url(r'^update_order/(?P<pk>[0-9]+)$', client_views.update_order, name='update_order'),

    url(r'^order_list', client_views.order_list, name='order_list'),
    url(r'^status_list', client_views.status_list, name='status_list'),

    url(r'^notification', client_views.notification, name='notification'),
]

officer/urls.py
from django.conf.urls import url
from django.views import generic
import officer.views as officer_views

app_name = 'officer'

urlpatterns = [
    # url(r'^dash/$', generic.FormView.as_view(
    #     form_class=form.RegistrationForm, template_name="dashboard/create_account.html")),
    url(r'^$', officer_views.personal_info, name='personal_info'),
    url(r'^profile', officer_views.profile, name='profile'),
    url(r'^contact', officer_views.contact, name='contact'),
    url(r'^picture', officer_views.picture, name='picture'),
    url(r'^password', officer_views.password, name='password'),

    url(r'^create_account', officer_views.create_account, name='create_account'),
    url(r'^delete_account', officer_views.delete_account, name='delete_account'),
    url(r'^reset_account_pass', officer_views.reset_account_pass, name='reset_account_pass'),

    url(r'^new_order', officer_views.new_order, name='new_order'),
    url(r'^view_order/(?P<pk>[0-9]+)$', officer_views.view_order, name='view_order'),
    url(r'^update_order/(?P<pk>[0-9]+)$', officer_views.update_order, name='update_order'),

    url(r'^account_list', officer_views.account_list, name='account_list'),
    url(r'^order_list', officer_views.order_list, name='order_list'),
    url(r'^status_list', officer_views.status_list, name='status_list'),

    url(r'^notification', officer_views.notification, name='notification'),
]

Notifications/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
# from order.models import Order
from core.models import Order

# Create your models here.


class Notifications(models.Model):
    from_user = models.ForeignKey(User, related_name='+')
    to_user = models.ForeignKey(User, related_name='+')
    order = models.ForeignKey(Order, related_name='+', blank=True, default=1)
    notification_message = models.TextField(max_length=250, null=True)
    notification_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'Notifications'

officer/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Order_List(models.Model):
    order_id = models.IntegerField()
    username = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    order_date = models.DateField()
    delivery_date = models.DateField()
    action = models.CharField(max_length=100)

Notifications/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render

# Create your views here.
from Notifications.models import Notifications


def general_notification(request, view):
    user = request.user
    unread = user.notifications.unread()
    __notification = Notifications()
    for msg in unread:
        __notification.from_user = msg.actor
        __notification.to_user = user
        __notification.order = msg.action_object
        __notification.notification_message = msg.verb
        __notification.notification_time = msg.timestamp
        print(msg.timestamp)
        __notification.save()
    all_notifications = Notifications.objects.filter(to_user=user)
    paginator = Paginator(all_notifications, 10)
    page = request.GET.get('page', 1) # returns the 1st page
    try:
        notification_list = paginator.page(page)
    except PageNotAnInteger:
        notification_list = paginator.page(1)
    except EmptyPage:
        notification_list = paginator.page(paginator.num_pages)
    return render(request, view, {
        'unread': unread,
        'notification_list': notification_list
    })

officer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

try:
    from BytesIO import BytesIO
except ImportError:
    from io import BytesIO
from django.core.files.storage import default_storage as storage

import os

from PIL import Image
from django.conf import settings as django_settings
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect, get_object_or_404
from django.shortcuts import render
from django.utils.datastructures import MultiValueDictKeyError
from notifications.signals import notify

from Notifications.views import general_notification
from OpenGMS.function_util import group_required
from authentication.models import NewUser, Employee
from core.models import Order, OrderHistory
from officer.form import ProfileForm, ChangePasswordForm, ContactForm, NewOrderForm


@login_required
@group_required('officer_group')
def personal_info(request):
    return render(request, 'dashboard/personal_info.html', {'user': request.user})


@login_required
@group_required('officer_group')
def profile(request):
    user = request.user
    if request.method == 'POST':
        print("Profile form submitted")
        form = ProfileForm(request.POST)
        if form.is_valid():
            print("Profile form Valid")
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.employee.date_of_birth = form.cleaned_data.get('date_of_birth')
            user.employee.sex = form.cleaned_data.get('sex')
            user.employee.designation = form.cleaned_data.get('designation')
            user.employee.job_title = form.cleaned_data.get('job_title')
            user.email = form.cleaned_data.get('email')
            user.employee.about = form.cleaned_data.get('about')

            if user.profile.account_flag == 1:
                user.profile.account_flag = 2
            user.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your profile is successfully saved.')
            if user.profile.account_flag != 0:
                return redirect('officer:contact')

        else:
            messages.add_message(request,
                                 messages.ERROR,
                                 'Your profile isn\'t saved.')

    else:
        form = ProfileForm(instance=user, initial={
            'first_name': user.first_name,
            'last_name': user.last_name,
            'date_of_birth': user.employee.date_of_birth,
            'sex': user.employee.sex,
            'designation': user.employee.designation,
            'job_title': user.employee.job_title,
            'email': user.email,
            'about': user.employee.about,
        })
    # form = ProfileForm()
    return render(request, 'dashboard/profile.html', {'form': form})


@login_required
@group_required('officer_group')
def contact(request):
    # form = ContactForm()
    user = request.user
    if request.method == 'POST':
        print("Contact form submitted")
        form = ContactForm(request.POST)
        if form.is_valid():
            print("Contact form Valid")
            user.profile.address = form.cleaned_data.get('address')
            user.profile.city = form.cleaned_data.get('city')
            user.profile.state = form.cleaned_data.get('state')
            user.profile.country = form.cleaned_data.get('country')
            user.profile.zip_code = form.cleaned_data.get('zip_code')
            user.profile.phone_num = form.cleaned_data.get('phone_num')
            if user.profile.account_flag == 2:
                user.profile.account_flag = 1
            user.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your contact is successfully saved.')
            if user.profile.account_flag != 0:
                return redirect('officer:picture')
        else:
            messages.add_message(request,
                                 messages.ERROR,
                                 'Your contact isn\'t saved.')

    else:
        form = ContactForm(instance=user, initial={
            'address': user.profile.address,
            'city': user.profile.city,
            'state': user.profile.state,
            'country': user.profile.country,
            'zip_code': user.profile.zip_code,
            'phone_num': user.profile.phone_num,
        })
    return render(request, 'dashboard/contact.html', {'form': form})


@login_required
@group_required('officer_group')
def picture(request):
    user = request.user
    profile_pictures = 'profile_pictures/'
    if request.method == 'POST':
        _picture = request.FILES['picture']
        user_str = request.user.username + '_' + str(request.user.id) + '.jpg'
        filename = profile_pictures + user_str
        with storage.open(filename, 'wb+') as destination:
            for chunk in _picture.chunks():
                destination.write(chunk)
        destination = storage.open(filename, 'rb+')
        im = Image.open(destination)
        width, height = im.size
        if width > 400:
            new_width = 400
            new_height = 300  # (height * 400) / width
            new_size = new_width, new_height
            im.thumbnail(new_size, Image.ANTIALIAS)

            sfile = BytesIO()
            im.save(sfile, format='JPEG')
            destination.close()

            destination = storage.open(filename, 'wb+')
            destination.write(sfile.getvalue())
            destination.close()

        if user.profile.account_flag == 3:
            user.profile.account_flag = 4

        user.profile.profile_picture = '/profile_pictures/' + user_str
        user.save()

        if user.profile.account_flag != 0:
            return redirect('officer:password')

        return render(request, 'dashboard/picture.html')
    print (user.profile.profile_picture)
    return render(request, 'dashboard/picture.html')


@login_required
@group_required('officer_group')
def password(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get('new_password')
            user.set_password(new_password)
            if user.profile.account_flag == 4:
                user.profile.account_flag = 0
                new_user = NewUser.objects.get(user=user)
                new_user.delete()
            user.save()
            update_session_auth_hash(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 'Your password is successfully changed.')
            return redirect('officer:password')
        else:
            messages.add_message(request, messages.SUCCESS,
                                 'Your password isn\'t changed.')
            return redirect('officer:password')
    else:
        form = ChangePasswordForm(instance=user)
    return render(request, 'dashboard/password.html', {'form': form})


@login_required()
@group_required('officer_group')
def create_account(request):
    if request.method == 'POST':
        username = request.POST.get('user', False)
        email = request.POST.get('email', False)
        account_type = request.POST.get('account_type', False)
        print (username)
        print (email)
        print (account_type)

        account_types = {'Client': 0, 'Technical Officer': 1, 'Service Manager': 2, 'Production Manager': 3}
        if (username != False and email != False and account_type != False):
            if not User.objects.filter(username=username).exists():
                password = User.objects.make_random_password(length=10)
                print("Generated Password " + password)
                user = User.objects.create_user(username=username, email=email, password=password)
                user.profile.account_type = account_types[account_type]
                user.save()
                NewUser(user=user, password=password).save()
                messages.success(request, 'Created account successfully.')
            else:
                messages.error(request, 'Submitted form is not valid. User already exist.')

        else:
            messages.error(request, 'Submitted form is not valid. Try again.')
        return render(request, 'dashboard/create_account.html')
    else:
        return render(request, 'dashboard/create_account.html')


@login_required()
@group_required('officer_group')
def delete_account(request):
    return render(request, 'dashboard/delete_account.html')


@login_required()
@group_required('officer_group')
def reset_account_pass(request):
    if request.method == 'POST':
        username = request.POST.get('user', False)
        email = request.POST.get('email', False)
        print (username)
        print (email)

        if username != False and email != False:

            if User.objects.filter(username=username).exists():
                user = User.objects.filter(username=username)
                password = User.objects.make_random_password(length=10)
                print("Generated Password " + password)
                user[0].set_password(password)
                user[0].profile.account_flag = 1
                user[0].save()
                if not NewUser.objects.filter(user=user[0]).exists():
                    NewUser(user=user[0], password=password).save()

                messages.success(request, 'Reset password successful.')
            else:

officer/templates/dashboard/create_account.html
{% extends 'dashboard/dash.html' %}
{% load staticfiles %}
{#{% load material_form %}#}

{% block head %}

    <!-- Animate.css -->
    <link href="{% static 'extra/animate.css/animate.min.css' %}" rel="stylesheet">

{% endblock %}


{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><h4>{{ message }}</h4></li>
            {% endfor %}
        </ul>
    {% endif %}
    <div>
        <div class="login_wrapper">
            <div class="animate form login_form">
                <section class="login_content">
                    <form action="{% url "officer:create_account" %}" method="post">
                        {% csrf_token %}
                        <h1>Create Account</h1>
                        <div>
                            <input type="text" name="user" class="form-control" placeholder="Username" required=""/>
                        </div>
                        <div>
                            <input type="email" name="email" class="form-control" placeholder="Email" required=""/>
                        </div>
                        <div class="form-group">
                            <div>
                                <select class="form-control" name="account_type">
                                    <option>Account Type</option>
                                    <option>Client</option>
                                    <option>Service Manager</option>
                                    <option>Production Manager</option>
                                    <option>Technical Officer</option>
                                </select>
                            </div>
                        </div>
                        <div>
                            <button value="Submit" class="btn btn-dark">Create Account</button>
                        </div>

                        <div class="separator">
                        </div>
                    </form>
                </section>
            </div>

        </div>
    </div>

{% endblock %}

{% block js %}
{% endblock %}


officer/templates/dashboard/dash.html
{% load staticfiles %}
{% load notifications_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>OpenGMS</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    {% block head %}
    {% endblock %}
    <!-- Bootstrap -->
    <link href="{% static 'extra/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'extra/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'extra/nprogress.css' %}" rel="stylesheet">
    <!-- jQuery custom content scroller -->
    <link href="{% static 'extra/jquery.mCustomScrollbar.min.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">


</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col menu_fixed">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <a href="{% url 'officer:personal_info' %}" class="site_title">
                        <i class="fa fa-paw"></i>
                        <span>OpenGMS</span></a>
                </div>

                <div class="clearfix"></div>

                <!-- menu profile quick info -->
                <div class="profile clearfix">
                    <div class="profile_pic">
                        {% if  user.profile.profile_picture %}
                            <img src="{{ user.profile.profile_picture.url }}" alt="..."
                                 class="img-circle profile_img">
                        {% else %}
                            <img src="{% static 'images/user.png' %}" class="img-circle profile_img">
                        {% endif %}
                    </div>
                    <div class="profile_info">
                        <span>Welcome,</span>
                        <h2>{{ user.profile.get_screen_name }}</h2>
                    </div>
                </div>
                <!-- /menu profile quick info -->

                <br/>

                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <h2>Technical Manager</h2>
                        <ul class="nav side-menu">
                            <li><a><i class="fa fa-edit"></i> Update Info <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{% url 'officer:profile' %}"> Profile </a></li>
                                    <li><a href="{% url 'officer:contact' %}"> Contact Info </a></li>
                                    <li><a href="{% url 'officer:picture' %}"> Picture </a></li>
                                    <li><a href="{% url 'officer:password' %}"> Password </a></li>
                                </ul>
                            </li>
                            <li><a><i class="fa fa-user-plus"></i> Manage Account <span
                                    class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{% url 'officer:create_account' %}"> Create Account </a></li>
                                    <li><a href="{% url 'officer:delete_account' %}"> Delete Account </a></li>
                                    <li><a href="{% url 'officer:reset_account_pass' %}"> Reset Password </a></li>
                                </ul>
                            </li>
                            <li><a><i class="fa fa-plus"></i> Submit New Data
                                <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{% url 'officer:new_order' %}"> New Order </a></li>
                                    <li><a href="#"> New Form </a></li>
                                </ul>
                            </li>
                            <li><a><i class="fa fa-info"></i> Change Data
                                <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{% url 'officer:account_list' %}"> All Accounts </a></li>
                                    <li><a href="{% url 'officer:order_list' %}"> All Orders </a></li>
                                    <li><a href="#"> All Forms </a></li>
                                </ul>
                            </li>
                            <li><a><i class="fa fa-bar-chart-o"></i> Data Status <span
                                    class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{% url 'officer:status_list' %}"> Status </a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>

                </div>
                <!-- /sidebar menu -->
            </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                               aria-expanded="false">
                                {% if  user.profile.profile_picture %}
                                    <img src="{{ user.profile.profile_picture.url }}" alt="">
                                {% else %}
                                    <img src="{% static 'images/user.png' %}" alt="">
                                {% endif %}
                                {{ user.get_full_name }}
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li><a href="{% url 'officer:personal_info' %}"> Profile</a></li>
                                <li>
                                    <a href="{% url 'officer:profile' %}">
                                        <span>Settings</span>
                                    </a>
                                </li>
                                <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                            </ul>
                        </li>
                        <li role="presentation" class="dropdown">
                            <a href="{% url 'officer:notification' %}" id="notifications" title="Notification">
                                <i class="fa fa-bell-o"></i>
                                {% live_notify_badge classes="badge" %}
                                {% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
                                {% live_notify_list classes="dropdown-menu" %}
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /top navigation -->


        <!-- page content -->
        <div class="right_col" role="main">
            <div class="container expand-on-small-only">
                {% block content %}{% endblock %}
            </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
            <div class="pull-right">
                Open Source Garments Management System by <a href="https://ajoydas.com">Ajoy Das</a>
            </div>
            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    </div>
</div>

{#    <!-- jQuery -->#}
{#    {% include 'dashboard/extra/jquery/dist/jquery.min.js' %}#}
{#    <script src="extra/jquery/dist/jquery.min.js"></script>#}
{#    <!-- Bootstrap -->#}
{#    {% include 'dashboard/extra/bootstrap/dist/js/bootstrap.min.js' %}#}
{#    <script src="extra/bootstrap/dist/js/bootstrap.min.js"></script>#}
{#    <!-- FastClick -->#}
{#    {% include 'dashboard/extra/fastclick/lib/fastclick.js' %}#}
{#    <script src="extra/fastclick/lib/fastclick.js"></script>#}
{#    <!-- NProgress -->#}
{#    {% include 'dashboard/extra/nprogress/nprogress.js' %}#}
{#    <script src="extra/nprogress/nprogress.js"></script>#}
{#    <!-- jQuery custom content scroller -->#}
{#    {% include 'dashboard/extra/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}#}
{#    <script src="extra/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>#}
{##}
{#    <!-- Custom Theme Scripts -->#}
{#    {% include 'dashboard/build/js/custom.min.js' %}#}
{#    <script src="build/js/custom.min.js"></script>#}

<script src="{% static 'extra/jquery/dist/jquery.min.js' %}"></script>
{#    <link href="extra/bootstrap.min.css" rel="stylesheet">#}
<!-- Font Awesome -->
<script src="{% static 'extra/bootstrap/dist/js/bootstrap.min.js' %}"></script>
{#    <link href="extra/font-awesome/css/font-awesome.min.css" rel="stylesheet">#}
<!-- NProgress -->
<script src="{% static 'extra/fastclick/lib/fastclick.js' %}"></script>

{#    <link href="extra/nprogress.css" rel="stylesheet">#}
<!-- jQuery custom content scroller -->
<script src="{% static 'extra/nprogress/nprogress.js' %}"></script>

{#  {% include 'dashboard/extra/jquery.mCustomScrollbar.min.css' %}#}
{#    <link href="extra/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>#}

<!-- Custom Theme Style -->
<script src="{% static 'extra/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}"></script>

{#  {% include 'dashboard/build/css/custom.min.css' %}#}
<script src="{% static 'build/js/custom.min.js' %}"></script>

{% block js %}
{% endblock %}
</body>
</html>

officer/templates/dashboard/reset_account_pass.html
{% extends 'dashboard/dash.html' %}
{% load staticfiles %}
{#{% load material_form %}#}

{% block head %}

    <!-- Animate.css -->
    <link href="{% static 'extra/animate.css/animate.min.css' %}" rel="stylesheet">

{% endblock %}


{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><h4>{{ message }}</h4></li>
            {% endfor %}
        </ul>
    {% endif %}
    <div>
        <div class="login_wrapper">
            <div class="animate form login_form">
                <section class="login_content">
                    <form action="{% url "officer:reset_account_pass" %}" method="post">
                        {% csrf_token %}
                        <h1>Reset Password</h1>
                        <div>
                            <input type="text" name="user" class="form-control" placeholder="Username" required=""/>
                        </div>
                        <div>
                            <input type="email" name="email" class="form-control" placeholder="Email" required=""/>
                        </div>
                        <div>
                            <button value="Submit" class="btn btn-dark">Reset Password</button>
                        </div>

                        <div class="separator">
                        </div>
                    </form>
                </section>
            </div>

        </div>
    </div>

{% endblock %}

{% block js %}
{% endblock %}
