OpenGMS/urls.py
import notifications
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views import generic
import notifications.urls

from core import views as core_views
from autocompleteAPI import views as autocomplete_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', core_views.home, name='home'),
    # url(r'^login', generic.FormView.as_view(
    #     form_class=core_form.LogInForm, template_name="core/base_form.html",success_url='loginpost'), name="login"),
    url(r'^login', core_views.loginview, name='login'),
    url(r'^logout', core_views.logoutview, name='logout'),
    # url(r'^login', auth_views.login, {'template_name': 'core/login.html'},
    #     name='login'),
    url(r'^auth/', include('authentication.urls')),
    url(r'^officer/', include('officer.urls')),
    url(r'^client/', include('client.urls')),
    url(r'^production/', include('production.urls')),
    url(r'^service/', include('service.urls')),

    # notification
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # rest API for autocomplete
    url('^api/clients/', autocomplete_views.list, name='clientsAPI'),

]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

client/urls.py
from django.conf.urls import url
from django.views import generic
import client.views as client_views

app_name = 'client'

urlpatterns = [
    url(r'^$', client_views.personal_info, name='personal_info'),
    url(r'^profile', client_views.profile, name='profile'),
    url(r'^contact', client_views.contact, name='contact'),
    url(r'^picture', client_views.picture, name='picture'),
    url(r'^password', client_views.password, name='password'),

    # url(r'^create_account', client_views.create_account, name='create_account'),
    # url(r'^delete_account', client_views.delete_account, name='delete_account'),
    # url(r'^reset_account_pass', client_views.reset_account_pass, name='reset_account_pass'),

    url(r'^new_order', client_views.new_order, name='new_order'),
    url(r'^view_order/(?P<pk>[0-9]+)$', client_views.view_order, name='view_order'),
    url(r'^update_order/(?P<pk>[0-9]+)$', client_views.update_order, name='update_order'),

    url(r'^order_list', client_views.order_list, name='order_list'),
    url(r'^status_list', client_views.status_list, name='status_list'),

    url(r'^notification', client_views.notification, name='notification'),
]

production/urls.py
from django.conf.urls import url
from django.views import generic
import production.views as production_views

app_name = 'production'

urlpatterns = [
    # url(r'^dash/$', generic.FormView.as_view(
    #     form_class=form.RegistrationForm, template_name="dashboard/create_account.html")),
    url(r'^$', production_views.personal_info, name='personal_info'),
    url(r'^profile', production_views.profile, name='profile'),
    url(r'^contact', production_views.contact, name='contact'),
    url(r'^picture', production_views.picture, name='picture'),
    url(r'^password', production_views.password, name='password'),

    url(r'^view_order/(?P<pk>[0-9]+)$', production_views.view_order, name='view_order'),
    url(r'^update_order/(?P<pk>[0-9]+)$', production_views.update_order, name='update_order'),

    url(r'^order_list', production_views.order_list, name='order_list'),
    url(r'^status_list', production_views.status_list, name='status_list'),

    url(r'^notification', production_views.notification, name='notification'),
    url(r'^estimate/(?P<pk>[0-9]+)', production_views.estimate, name='estimate'),
    url(r'^estimate_list/', production_views.estimate_list, name='estimate_list'),

    url(r'^estimate_train', production_views.train_estimator, name='estimate_train'),

]

Notifications/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
# from order.models import Order
from core.models import Order

# Create your models here.


class Notifications(models.Model):
    from_user = models.ForeignKey(User, related_name='+')
    to_user = models.ForeignKey(User, related_name='+')
    order = models.ForeignKey(Order, related_name='+', blank=True, default=1)
    notification_message = models.TextField(max_length=250, null=True)
    notification_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'Notifications'

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models


#onlinebookshare> mylibrary> views.py/ model.py
class Order(models.Model):
    client = models.ForeignKey(User, related_name="client_username", null=True,
                               on_delete=models.SET_NULL)
    submitted_by = models.ForeignKey(User, related_name="submitted_by")
    approved_by = models.ForeignKey(User, related_name="approved_by", null=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    order_status = models.CharField(max_length=50)

    client_name = models.CharField(max_length=50, null=True)
    order_type = models.CharField(max_length=20)
    design = models.FileField(upload_to='designs/', null=True, blank=True)
    deadline = models.DateField()
    quantity = models.IntegerField(default=0)
    budget = models.IntegerField(default=0)
    shipping_address = models.CharField(max_length=300, null=True)
    specification = models.CharField(max_length=300, null=True)
    progress = models.IntegerField(default=0)

    # o-> not verified yet , 1-> approved , 2-> rejected
    approved = models.IntegerField(default=0)
    review_note = models.CharField(max_length=200, null=True)

    class Meta:
        db_table = 'orders'


class OrderHistory(models.Model):
    order = models.ForeignKey(Order)
    client = models.ForeignKey(User, related_name="client_username_history", null=True,
                               on_delete=models.SET_NULL)
    submitted_by = models.ForeignKey(User, related_name="submitted_by_history")
    approved_by = models.ForeignKey(User, related_name="approved_by_history", null=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    order_status = models.CharField(max_length=50)

    client_name = models.CharField(max_length=50, null=True)
    order_type = models.CharField(max_length=20)
    design = models.FileField(upload_to='designs/', null=True, blank=True)
    deadline = models.DateField()
    quantity = models.IntegerField(default=0)
    budget = models.IntegerField(default=0)
    shipping_address = models.CharField(max_length=300, null=True)
    specification = models.CharField(max_length=300, null=True)
    progress = models.IntegerField(default=0)

    approved = models.IntegerField(default=0)
    review_note = models.CharField(max_length=200, null=True)

    class Meta:
        db_table = 'order_histories'

    def __init__(self, order, *args, **kwargs):
        super(OrderHistory, self).__init__(*args, **kwargs)
        self.order = order
        self.client = order.client
        self.submitted_by = order.submitted_by
        self.approved_by = order.approved_by
        self.updated_at = order.updated_at
        self.order_status = order.order_status

        self.client_name = order.client_name
        self.order_type = order.order_type
        self.design = order.design
        self.deadline = order.deadline
        self.quantity = order.quantity
        self.budget = order.budget
        self.shipping_address = order.shipping_address
        self.specification = order.specification
        self.progress = order.progress

        self.approved = order.approved
        self.review_note = order.review_note

    def __init__(self, *args, **kwargs):
        super(OrderHistory, self).__init__(*args, **kwargs)

    def copy(self, order):
        self.order = order
        self.client = order.client
        self.submitted_by = order.submitted_by
        self.approved_by = order.approved_by
        self.updated_at = order.updated_at
        self.order_status = order.order_status

        self.client_name = order.client_name
        self.order_type = order.order_type
        self.design = order.design
        self.deadline = order.deadline
        self.quantity = order.quantity
        self.budget = order.budget
        self.shipping_address = order.shipping_address
        self.specification = order.specification
        self.progress = order.progress

        self.approved = order.approved
        self.review_note = order.review_note



production/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Order_List(models.Model):
    order_id = models.IntegerField()
    username = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    order_date = models.DateField()
    delivery_date = models.DateField()
    action = models.CharField(max_length=100)

Notifications/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render

# Create your views here.
from Notifications.models import Notifications


def general_notification(request, view):
    user = request.user
    unread = user.notifications.unread()
    __notification = Notifications()
    for msg in unread:
        __notification.from_user = msg.actor
        __notification.to_user = user
        __notification.order = msg.action_object
        __notification.notification_message = msg.verb
        __notification.notification_time = msg.timestamp
        print(msg.timestamp)
        __notification.save()
    all_notifications = Notifications.objects.filter(to_user=user)
    paginator = Paginator(all_notifications, 10)
    page = request.GET.get('page', 1) # returns the 1st page
    try:
        notification_list = paginator.page(page)
    except PageNotAnInteger:
        notification_list = paginator.page(1)
    except EmptyPage:
        notification_list = paginator.page(paginator.num_pages)
    return render(request, view, {
        'unread': unread,
        'notification_list': notification_list
    })

production/templates/production/contact.html
{% extends 'production/dash.html' %}
{% load i18n %}

{#{% block head %}#}
{#    {% block title %} Account Settings {% endblock %}#}
{#{% endblock %}#}
{% block content %}

     <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Edit Profile' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'production:contact' %}">
        {% csrf_token %}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

{% block js %}
{% endblock %}

production/templates/production/dash.html
{% load staticfiles %}
{% load notifications_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>OpenGMS</title>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
      {% block head %}
    {% endblock %}
    <!-- Bootstrap -->
   <link href="{% static 'extra/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
     <link href="{% static 'extra/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
      <!-- NProgress -->
   <link href="{% static 'extra/nprogress.css' %}" rel="stylesheet">
    <!-- jQuery custom content scroller -->
   <link href="{% static 'extra/jquery.mCustomScrollbar.min.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
   <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">




  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col menu_fixed">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
                    <a href="{% url 'production:personal_info' %}" class="site_title">
                        <i class="fa fa-paw"></i>
                        <span>OpenGMS</span></a>
                </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
                <div class="profile clearfix">
                    <div class="profile_pic">
                        {% if  user.profile.profile_picture %}
                            <img src="{{ user.profile.profile_picture.url }}" alt="..."
                                 class="img-circle profile_img">
                        {% else %}
                            <img src="{% static 'images/user.png' %}" class="img-circle profile_img">
                        {% endif %}
                    </div>
                    <div class="profile_info">
                        <span>Welcome,</span>
                        <h2>{{ user.profile.get_screen_name }}</h2>
                    </div>
                </div>
                <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h2>Production Manager</h2>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-edit"></i> Update Info <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'production:profile'%}"> Profile </a></li>
                        <li><a href="{% url 'production:contact'%}"> Contact Info </a></li>
                        <li><a href="{% url 'production:picture' %}"> Picture </a></li>
                        <li><a href="{% url 'production:password' %}"> Password </a></li>
                    </ul>
                  </li>
{#                  <li><a><i class="fa fa-plus"></i> Submit New Order#}
{#                    <span class="fa fa-chevron-down"></span></a>#}
{#                    <ul class="nav child_menu">#}
{#                      <li><a href="{% url 'production:new_order' %}"> New Order </a></li>#}
{#                    </ul>#}
{#                  </li>#}
                  <li><a><i class="fa fa-info"></i> Order History
                    <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'production:order_list' %}"> Order List </a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-bar-chart-o"></i> Data Status <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'production:status_list' %}"> Order Status </a></li>
                        <li><a href="{% url 'production:estimate_list' %}"> Estimate List </a></li>
                    </ul>
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

               <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                               aria-expanded="false">
                                {% if  user.profile.profile_picture %}
                                    <img src="{{ user.profile.profile_picture.url }}" alt="">
                                {% else %}
                                    <img src="{% static 'images/user.png' %}" alt="">
                                {% endif %}
                                {{ user.get_full_name }}
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li><a href="{% url 'production:personal_info' %}"> Profile</a></li>
                                <li>
                                    <a href="{% url 'production:profile' %}">
                                        <span>Settings</span>
                                    </a>
                                </li>
                                <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                                </li>
                            </ul>
                        </li>
                   <li role="presentation" class="dropdown">
                       <a href="{% url 'production:notification' %}" id="notifications" title="Notification">
                           <i class="fa fa-bell-o"></i>
                           {% live_notify_badge classes="badge" %}
                           {% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
                           {% live_notify_list classes="dropdown-menu" %}
                       </a>
                   </li>
                    </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->


        <!-- page content -->
        <div class="right_col" role="main">
              <div class="container expand-on-small-only">
                {% block content %}{% endblock %}
              </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Open Source Garments Management System by <a href="https://ajoydas.com">Ajoy Das</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

{#    <!-- jQuery -->#}
{#    {% include 'dashboard/extra/jquery/dist/jquery.min.js' %}#}
{#    <script src="extra/jquery/dist/jquery.min.js"></script>#}
{#    <!-- Bootstrap -->#}
{#    {% include 'dashboard/extra/bootstrap/dist/js/bootstrap.min.js' %}#}
{#    <script src="extra/bootstrap/dist/js/bootstrap.min.js"></script>#}
{#    <!-- FastClick -->#}
{#    {% include 'dashboard/extra/fastclick/lib/fastclick.js' %}#}
{#    <script src="extra/fastclick/lib/fastclick.js"></script>#}
{#    <!-- NProgress -->#}
{#    {% include 'dashboard/extra/nprogress/nprogress.js' %}#}
{#    <script src="extra/nprogress/nprogress.js"></script>#}
{#    <!-- jQuery custom content scroller -->#}
{#    {% include 'dashboard/extra/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}#}
{#    <script src="extra/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>#}
{##}
{#    <!-- Custom Theme Scripts -->#}
{#    {% include 'dashboard/build/js/custom.min.js' %}#}
{#    <script src="build/js/custom.min.js"></script>#}

  <script src="{% static 'extra/jquery/dist/jquery.min.js' %}"></script>
{#    <link href="extra/bootstrap.min.css" rel="stylesheet">#}
    <!-- Font Awesome -->
    <script src="{% static 'extra/bootstrap/dist/js/bootstrap.min.js' %}"></script>
{#    <link href="extra/font-awesome/css/font-awesome.min.css" rel="stylesheet">#}
    <!-- NProgress -->
    <script src="{% static 'extra/fastclick/lib/fastclick.js' %}"></script>

{#    <link href="extra/nprogress.css" rel="stylesheet">#}
    <!-- jQuery custom content scroller -->
  <script src="{% static 'extra/nprogress/nprogress.js' %}"></script>

{#  {% include 'dashboard/extra/jquery.mCustomScrollbar.min.css' %}#}
{#    <link href="extra/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>#}

    <!-- Custom Theme Style -->
  <script src="{% static 'extra/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}"></script>

{#  {% include 'dashboard/build/css/custom.min.css' %}#}
    <script src="{% static 'build/js/custom.min.js' %}"></script>
      {% block js %}
    {% endblock %}
  </body>
</html>

production/templates/production/password.html
{% extends 'production/dash.html' %}
{% load i18n %}

{#{% block head %}#}
{#    {% block title %} Account Settings {% endblock %}#}
{#{% endblock %}#}
{% block content %}

     <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Change Password' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'production:password' %}">
        {% csrf_token %}
        {{ form.id }}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-3 control-label">{{ field.label }}</label>
            <div class="col-sm-9">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

{% block js %}
{% endblock %}

production/templates/production/update_order.html
{% extends 'production/dash.html' %}
{% load i18n %}
{% load staticfiles %}

{% block head %}
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
{% endblock %}
{% block content %}

    <div class="page-header">
        <h1>{% trans 'Update Order' %}</h1>
    </div>
    <div class="row" style="margin-top: 2em">
        <div class="col-md-9">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <h3 style="margin-top: 0">{% trans 'Update Order' %}</h3>
            <form enctype="multipart/form-data" class="form-horizontal" method="post"
                  action="{% url 'production:update_order' order.id %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="Client Username" class="col-sm-2 control-label">Client Username</label>
                    <div class="col-sm-10">

                        {#                        <input type="text" name="client_username" id="id_client_username" class="form-control"#}
                        {#                               maxlength="50">#}
                        <select class="js-data-example-ajax" style="width: 100mm" name="client_username">
                            {#                            <option></option>#}
                            {% if order.client.get_username %}
                                <option value="{{ order.client.id }}">{{ order.client.get_username }}</option>
                            {% endif %}
                        </select>

                    </div>
                </div>

                {% for field in form.visible_fields %}
                    <div class="form-group{% if field.errors %} has-error{% endif %}">
                        <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">
                            {{ field }}
                            {% if field.help_text %}
                                <span class="help-block">{{ field.help_text }}</span>
                            {% endif %}
                            {% for error in field.errors %}
                                <label class="control-label">{{ error }}</label>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}

                <div class="form-group">
                    <label for="Progress" class="col-sm-2 control-label">Progress (in %)</label>
                    <div class="col-sm-10">
                        <input name="progress" value="{{ order.progress }}" required="required" class="form-control"
                               id="id_progress" type="text">
                    </div>
                </div>

                <div class="form-group">
                    <label for="review_note" class="col-sm-2 control-label">Review Note</label>
                    <div class="col-sm-10">
                    <textarea name="review_note" maxlength="300" id="id_review_note" rows="4" class="form-control"
                              cols="40"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">{% trans 'Update' %}</button>
                    </div>
                </div>
            </form>
        </div>
        <div>

        </div>
    </div>

{% endblock %}

{% block js %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    {#    <script src="{% static 'js/select2.js' %}"></script>#}
    <script>window.jQuery || document.write('<script src="{%  static 'js/jquery.min.js' %}"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
            integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'js/holder.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.js-data-example-ajax').select2({
                ajax: {
                    url: "{% url 'clientsAPI'%}",
                    dataType: 'json',
                    {#					delay: 250,#}
                    data: function (params) {
                        var query = {
                            q: params.term
                        };
                        return query
                    },
                    results: function (data, params) {
                        return {
                            results: data
                        }
                    },
                    cache: true
                },
                placeholder: 'Search for a client username',
                escapeMarkup: function (markup) {
                    return markup;
                }, // let our custom formatter work
                minimumInputLength: 1,
                {#                templateResult: showName,#}
                templateSelection: formatSelection
            });

            function showName(repo) {
                return repo.text
            }

            function formatSelection(results) {
                return '<option value="' + results.id + '">' + results.text + '</option>'
            }
        });
    </script>

    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css"
          rel="stylesheet">
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>

    <script>
        $(function () {
            $('.datetime-input').datetimepicker({
                format: 'YYYY-MM-DD'
            });
        });
    </script>

{% endblock %}